name: ChangesetsSnapshot
description: A GitHub action to automate Changesets snapshot releases
runs:
  using: "node16"
  main: "dist/index.js"
inputs:
  tag:
    description: "The name of the tag to use for snapshot publishing"
    required: true
  cwd:
    description: Sets the cwd for the node process. Default to `process.cwd()`
    required: false
outputs:
  published:
    description: A boolean value to indicate whether a publishing is happened or not
  publishedPackages:
    description: >
      A JSON array to present the published packages. The format is `[{"name": "@xx/xx", "version": "1.2.0"}, {"name": "@xx/xy", "version": "0.8.9"}]`
  hasChangesets:
    description: A boolean about whether there were changesets. Useful if you want to create your own publishing functionality.
branding:
  icon: "package"
  color: "blue"
